// FORM CONTENT
export const SET_STEPA_CONTENT = 'SET_STEPA_CONTENT';
export const RESET_STEPA_CONTENT = 'RESET_NAMEVIEW_CONTENT';
export const SET_STEPC_CONTENT = 'SET_STEPC_CONTENT';
export const RESET_STEPC_CONTENT = 'RESET_STEPC_CONTENT';
export const SET_STEPB_CONTENT = 'SET_STEPB_CONTENT';
export const RESET_STEPB_CONTENT = 'RESET_STEPB_CONTENT';
export const SET_STEPD_CONTENT = 'SET_STEPD_CONTENT';
export const RESET_STEPD_CONTENT = 'RESET_STEPD_CONTENT';